defaults:
    - task: cls
    - model: ssg
    - task_model: ${defaults.0.task}-${defaults.1.model}

hydra:
  run:
    dir: outputs

gpus:
    - 0

weights: unkown
input: unkown

batch_file: ???
batch_dir: ???

optimizer: ???

task_model: ???

model: ???

distrib_backend: dp
