defaults:
    - task: cls
    - model: ssg
    - task_model: ${defaults.0.task}-${defaults.1.model}

hydra:
  run:
    dir: outputs

gpus:
    - 0

#predict
weights: unkown
input: unkown

#train
batch_file: unkown
batch_dir: unkown
output: unkown
classes: 0

optimizer: ???

task_model: ???

model: ???

distrib_backend: dp
